import { Hole } from './hole';

export interface CourseData {
    id: string,
    includes: string,
    courseId: number,
    statusId: number,
    status: string,
    courseTypeId: number,
    courseType: string,
    practiceAreaId: number,
    measurementType: string,
    mediaId: number,
    holeCount: number,
    lat: number,
    lng: number,
    popularityOneWeek: number,
    popularityThreeMonth: number,
    distanceFromMeKilometers: number,
    distanceFromMeMiles: number,
    localRankOneWeek: number,
    localRankThreeMonth: number,
    globalRankOneWeek: number,
    globalRankThreeMonth: number,
    localMaxRank: number,
    globalMaxRank: number,
    name: string,
    addr1: string,
    addr2?: any,
    city: string,
    stateOrProvince: string,
    country: string,
    zipCode: string,
    phone: string,
    website: string,
    courseDesigner?: any,
    courseArchitect?: any,
    accomodations?: any,
    hours?: any,
    fax?: any,
    fees?: any,
    description?: any,
    thumbnail: string,
    holes: Hole[]
}